version: "3"
services:
  wrangler-db:
    image: container-registry.oracle.com/database/enterprise:19.3.0.0
    restart: always
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PDB: wrangler
      ORACLE_PWD: fusion
    volumes:
      - wranglerdata:/opt/oracle/oradata

  wrangler_backend:
    restart: always
    container_name: wrangler-backend
    build:
      context: .
      args:
        - UID=$UID
        - GID=$EUID
      dockerfile: Dockerfile
    entrypoint: ["./docker-entrypoint.sh"]
    tty: true
    stdin_open: true
    ports:
      - "9999:9999"
    environment:
      LD_LIBRARY_PATH: /app/winstantclient_19_6
    volumes:
      - .:/app
    depends_on:
      - wrangler-db

volumes:
  wranglerdata:
