--------------------------------------------------------
--  File created - Wednesday-October-28-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View VW_DOCUMENTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "FUSION"."VW_DOCUMENTS" ("DOCLIBID", "UPDATEDDATE", "UPDATEDBY", "CREATEDDATE", "CREATEDBY", "SUBJECT", "DESCRIPTION", "COMMENTS", "PUBLISHDATE", "EFFECTIVEDATE", "DONOTIFY", "RESPONSENEEDED", "DOCTYPE", "DOCSUBTYPE", "LAUNCHID", "LAUNCHMODE", "REPLYTO", "REPLYTONAME", "RESPONSEFORM", "PARENTID", "INCCATEGORY", "CREATEDORG", "UPDATEDORG", "NC4LEVEL", "SEVERITY", "ORGANIZATIONID", "STARTTIME", "ENDTIME", "LOCATIONS", "NC4ATTRS", "CATEGORIES_2", "CATEGORIES", "NOTIFYGROUPS", "NOTIFYMEMBERS", "ATTACHMENTS", "LINKS", "NC4READERS", "NC4AUTHORS", "NC4EDITABLE") AS 
  SELECT 
  V."DOCLIBID",V."UPDATEDDATE",V."UPDATEDBY",V."CREATEDDATE",V."CREATEDBY",V."SUBJECT",V."DESCRIPTION",V."COMMENTS",V."PUBLISHDATE",V."EFFECTIVEDATE",V."DONOTIFY",V."RESPONSENEEDED",V."DOCTYPE",V."DOCSUBTYPE",V."LAUNCHID",V."LAUNCHMODE",V."REPLYTO",V."REPLYTONAME",V."RESPONSEFORM",V."PARENTID",V."INCCATEGORY",V."CREATEDORG",V."UPDATEDORG",V."NC4LEVEL",V."SEVERITY",V."ORGANIZATIONID",V."STARTTIME",V."ENDTIME",V."LOCATIONS",V."NC4ATTRS",V."CATEGORIES_2",V."CATEGORIES",V."NOTIFYGROUPS",V."NOTIFYMEMBERS",V."ATTACHMENTS",V."LINKS",V."NC4READERS",V."NC4AUTHORS",
  USER_DATA_POLICY.CAN_EDIT(V.NC4AUTHORS) NC4EDITABLE
FROM 
  (SELECT /*+ UNNEST(@nc4readers) */
    T.*,
    CAST(MULTISET(SELECT NC4TYPES.NC4_LOCATION(LABEL, STREET, CITY, COUNTY, STATE, POSTAL, COUNTRY, REGION, WKTGEOMS)
                  FROM TBL_DOCLOCS DL 
                  WHERE DL.DOCLIBID = T.DOCLIBID  
        ) AS NC4TYPES.NC4_LOCATION_T) LOCATIONS,
    CAST(MULTISET(SELECT NC4TYPES.NC4_ATTR(ATTRID, ATTRLABEL, CHARVALUE, NUMVALUE, DATEVALUE, VALUELABEL, INCLUDE_MAP, INCLUDE_NOTIF)
                  FROM TBL_DOCATTRS DA 
                  WHERE DA.DOCLIBID = T.DOCLIBID
        ) AS NC4TYPES.NC4_ATTR_T) NC4ATTRS,
    CAST(MULTISET(SELECT NC4TYPES.NC4_ID_LABEL(CATEGORYID, FIELDNAME )
                  FROM TBL_CATUSAGE GN 
                  WHERE GN.DOCLIBID = T.DOCLIBID  
        ) AS NC4TYPES.NC4_ID_LABEL_T) CATEGORIES_2,
    CAST(MULTISET(SELECT CATEGORYID 
                  FROM TBL_CATUSAGE GN 
                  WHERE GN.DOCLIBID = T.DOCLIBID  
        ) AS NC4TYPES.NC4_CHAR_ARRAY) CATEGORIES,
    CAST(MULTISET(SELECT GROUPID 
                  FROM TBL_NOTIFYLIST GN 
                  WHERE GROUPID IS NOT NULL AND GN.DOCLIBID = T.DOCLIBID  
        ) AS NC4TYPES.NC4_CHAR_ARRAY) NOTIFYGROUPS,
    CAST(MULTISET(SELECT MEMBERID 
                  FROM TBL_NOTIFYLIST GN 
                  WHERE MEMBERID IS NOT NULL AND GN.DOCLIBID = T.DOCLIBID  
        ) AS NC4TYPES.NC4_CHAR_ARRAY) NOTIFYMEMBERS,
    CAST(MULTISET(SELECT NC4TYPES.NC4_ATTACHMENT(DOCATTACHID, LABEL, MIMETYPE, length(ATTACHDATA), FILENAME )
                  FROM TBL_DOCATTACH D 
                  WHERE D.DOCLIBID = T.DOCLIBID  AND LINKDATA IS NULL
        ) AS NC4TYPES.NC4_ATTACHMENT_T) ATTACHMENTS,
    CAST(MULTISET(SELECT NC4TYPES.NC4_ATTACHMENT(DOCATTACHID, LABEL, NULL, 0, NULL)
                  FROM TBL_DOCATTACH D 
                  WHERE D.DOCLIBID = T.DOCLIBID  AND LINKDATA IS NOT NULL
        ) AS NC4TYPES.NC4_ATTACHMENT_T) LINKS,
    CAST(MULTISET(SELECT SCOPEVAL 
                  FROM TBL_DOCLIB_SCOPE SC 
                  WHERE SC.DOCLIBID = T.DOCLIBID AND SC.RWFLAG = 'R'
        ) AS NC4TYPES.NC4_CHAR_ARRAY) NC4READERS,
    CAST(MULTISET(SELECT SCOPEVAL 
                  FROM TBL_DOCLIB_SCOPE SC 
                  WHERE SC.DOCLIBID = T.DOCLIBID AND SC.RWFLAG = 'W'
        ) AS NC4TYPES.NC4_CHAR_ARRAY) NC4AUTHORS
  FROM 
    TBL_DOCLIB T) V
 ;
