--------------------------------------------------------
--  File created - Wednesday-October-28-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_CATEGORY
--------------------------------------------------------

  CREATE TABLE "FUSION"."TBL_CATEGORY" 
   (	"CATEGORYID" VARCHAR2(32 CHAR), 
	"UPDATEDDATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATEDBY" VARCHAR2(64 CHAR), 
	"UPDATEDORG" VARCHAR2(128 CHAR), 
	"CREATEDDATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CREATEDBY" VARCHAR2(64 CHAR), 
	"CREATEDORG" VARCHAR2(128 CHAR), 
	"COMPONENT" VARCHAR2(32 CHAR), 
	"ROOT" VARCHAR2(64 CHAR), 
	"NODE" VARCHAR2(128 CHAR), 
	"FULLYQUALIFIED" VARCHAR2(512 CHAR), 
	"PARENTCAT" VARCHAR2(32 CHAR), 
	"DESCRIPTION" VARCHAR2(4000 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUSION" ;
--------------------------------------------------------
--  DDL for Index IDX_FK_CATEGORY_CATEGORY
--------------------------------------------------------

  CREATE INDEX "FUSION"."IDX_FK_CATEGORY_CATEGORY" ON "FUSION"."TBL_CATEGORY" ("PARENTCAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUSION" ;
--------------------------------------------------------
--  DDL for Index PK_CATEGORY
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUSION"."PK_CATEGORY" ON "FUSION"."TBL_CATEGORY" ("CATEGORYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUSION" ;
--------------------------------------------------------
--  Constraints for Table TBL_CATEGORY
--------------------------------------------------------

  ALTER TABLE "FUSION"."TBL_CATEGORY" ADD SUPPLEMENTAL LOG DATA (UNIQUE INDEX) COLUMNS;
  ALTER TABLE "FUSION"."TBL_CATEGORY" ADD SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS;
  ALTER TABLE "FUSION"."TBL_CATEGORY" ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
  ALTER TABLE "FUSION"."TBL_CATEGORY" ADD CONSTRAINT "PK_CATEGORY" PRIMARY KEY ("CATEGORYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUSION"  ENABLE;
  ALTER TABLE "FUSION"."TBL_CATEGORY" ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
  ALTER TABLE "FUSION"."TBL_CATEGORY" MODIFY ("FULLYQUALIFIED" NOT NULL ENABLE);
  ALTER TABLE "FUSION"."TBL_CATEGORY" MODIFY ("NODE" NOT NULL ENABLE);
  ALTER TABLE "FUSION"."TBL_CATEGORY" MODIFY ("ROOT" NOT NULL ENABLE);
  ALTER TABLE "FUSION"."TBL_CATEGORY" MODIFY ("COMPONENT" NOT NULL ENABLE);
  ALTER TABLE "FUSION"."TBL_CATEGORY" MODIFY ("CREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "FUSION"."TBL_CATEGORY" MODIFY ("UPDATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "FUSION"."TBL_CATEGORY" MODIFY ("CATEGORYID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TBL_CATEGORY
--------------------------------------------------------

  ALTER TABLE "FUSION"."TBL_CATEGORY" ADD CONSTRAINT "FK_CATEGORY_CATEGORY" FOREIGN KEY ("PARENTCAT")
	  REFERENCES "FUSION"."TBL_CATEGORY" ("CATEGORYID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRDT_TBL_CATEGORY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "FUSION"."TRDT_TBL_CATEGORY" before insert or update on TBL_CATEGORY for each row begin  if trgdt_mgr.isdisabled = 0 then  if inserting then :new.createddate := systimestamp; :new.createdby := context_mgr.get_fullname;  :new.createdorg := context_mgr.get_orgname;  :new.updateddate := systimestamp; :new.updatedby := context_mgr.get_fullname; :new.updatedorg := context_mgr.get_orgname;  end if; if updating then :new.updateddate := systimestamp; :new.updatedby := context_mgr.get_fullname;  :new.updatedorg := context_mgr.get_orgname; end if; end if;  end; 









/
ALTER TRIGGER "FUSION"."TRDT_TBL_CATEGORY" ENABLE;
