--------------------------------------------------------
--  File created - Thursday-October-29-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ITEMLOCATIONS
--------------------------------------------------------

  CREATE TABLE "TRANSECUR"."ITEMLOCATIONS" 
   (	"ITEMID" NUMBER(10,0), 
	"LOCATIONID" NUMBER(5,0), 
	"PRIMARYLOCATION" NUMBER(1,0) DEFAULT 0, 
	"PRIMARY_ID" VARCHAR2(32 CHAR) DEFAULT SYS_GUID(), 
	"DAILYITEMS_KEY" VARCHAR2(32 CHAR), 
	"LOCATIONS_KEY" VARCHAR2(32 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUSION" ;
--------------------------------------------------------
--  DDL for Index PKY_ITEMLOCATIONS
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRANSECUR"."PKY_ITEMLOCATIONS" ON "TRANSECUR"."ITEMLOCATIONS" ("PRIMARY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUSION" ;
--------------------------------------------------------
--  DDL for Index IDX_ITEMLOCATIONS_I1001
--------------------------------------------------------

  CREATE INDEX "TRANSECUR"."IDX_ITEMLOCATIONS_I1001" ON "TRANSECUR"."ITEMLOCATIONS" ("ITEMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUSION" ;
--------------------------------------------------------
--  DDL for Index IDX_ITLOCS_LOCID_ITID
--------------------------------------------------------

  CREATE INDEX "TRANSECUR"."IDX_ITLOCS_LOCID_ITID" ON "TRANSECUR"."ITEMLOCATIONS" ("LOCATIONID", "ITEMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUSION" ;
--------------------------------------------------------
--  Constraints for Table ITEMLOCATIONS
--------------------------------------------------------

  ALTER TABLE "TRANSECUR"."ITEMLOCATIONS" MODIFY ("PRIMARYLOCATION" NOT NULL ENABLE);
  ALTER TABLE "TRANSECUR"."ITEMLOCATIONS" MODIFY ("LOCATIONID" NOT NULL ENABLE);
  ALTER TABLE "TRANSECUR"."ITEMLOCATIONS" MODIFY ("ITEMID" NOT NULL ENABLE);
  ALTER TABLE "TRANSECUR"."ITEMLOCATIONS" ADD CONSTRAINT "PKY_ITEMLOCATIONS" PRIMARY KEY ("PRIMARY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUSION"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ITEMLOCATIONS
--------------------------------------------------------

  ALTER TABLE "TRANSECUR"."ITEMLOCATIONS" ADD CONSTRAINT "FK_ITEMLOC_DAILYITEMS" FOREIGN KEY ("DAILYITEMS_KEY")
	  REFERENCES "TRANSECUR"."DAILYITEMS" ("PRIMARY_ID") ENABLE;
  ALTER TABLE "TRANSECUR"."ITEMLOCATIONS" ADD CONSTRAINT "FK_ITEMLOC_LOCATIONS" FOREIGN KEY ("LOCATIONS_KEY")
	  REFERENCES "TRANSECUR"."LOCATIONS" ("PRIMARY_ID") ENABLE;
